/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...path]': RouteRecordInfo<'/[...path]', '/:path(.*)', { path: ParamValue<true> }, { path: ParamValue<false> }>,
    '/auth': RouteRecordInfo<'/auth', '/auth', Record<never, never>, Record<never, never>, '/auth/' | '/auth/forgot-password' | '/auth/otp' | '/auth/sign-in' | '/auth/sign-in-2' | '/auth/sign-up'>,
    '/auth/': RouteRecordInfo<'/auth/', '/auth', Record<never, never>, Record<never, never>>,
    '/auth/forgot-password': RouteRecordInfo<'/auth/forgot-password', '/auth/forgot-password', Record<never, never>, Record<never, never>>,
    '/auth/otp': RouteRecordInfo<'/auth/otp', '/auth/otp', Record<never, never>, Record<never, never>>,
    '/auth/sign-in': RouteRecordInfo<'/auth/sign-in', '/auth/sign-in', Record<never, never>, Record<never, never>>,
    '/auth/sign-in-2': RouteRecordInfo<'/auth/sign-in-2', '/auth/sign-in-2', Record<never, never>, Record<never, never>>,
    '/auth/sign-up': RouteRecordInfo<'/auth/sign-up', '/auth/sign-up', Record<never, never>, Record<never, never>>,
    '/demo/': RouteRecordInfo<'/demo/', '/demo', Record<never, never>, Record<never, never>>,
    '/demo/ai-talk/': RouteRecordInfo<'/demo/ai-talk/', '/demo/ai-talk', Record<never, never>, Record<never, never>>,
    '/demo/analytics/': RouteRecordInfo<'/demo/analytics/', '/demo/analytics', Record<never, never>, Record<never, never>>,
    '/demo/apps/': RouteRecordInfo<'/demo/apps/', '/demo/apps', Record<never, never>, Record<never, never>>,
    '/demo/auth/': RouteRecordInfo<'/demo/auth/', '/demo/auth', Record<never, never>, Record<never, never>>,
    '/demo/auth/forgot-password': RouteRecordInfo<'/demo/auth/forgot-password', '/demo/auth/forgot-password', Record<never, never>, Record<never, never>>,
    '/demo/auth/otp': RouteRecordInfo<'/demo/auth/otp', '/demo/auth/otp', Record<never, never>, Record<never, never>>,
    '/demo/auth/sign-in': RouteRecordInfo<'/demo/auth/sign-in', '/demo/auth/sign-in', Record<never, never>, Record<never, never>>,
    '/demo/auth/sign-in-2': RouteRecordInfo<'/demo/auth/sign-in-2', '/demo/auth/sign-in-2', Record<never, never>, Record<never, never>>,
    '/demo/auth/sign-up': RouteRecordInfo<'/demo/auth/sign-up', '/demo/auth/sign-up', Record<never, never>, Record<never, never>>,
    '/demo/billing/': RouteRecordInfo<'/demo/billing/', '/demo/billing', Record<never, never>, Record<never, never>>,
    '/demo/dev/api-docs': RouteRecordInfo<'/demo/dev/api-docs', '/demo/dev/api-docs', Record<never, never>, Record<never, never>>,
    '/demo/dev/examples': RouteRecordInfo<'/demo/dev/examples', '/demo/dev/examples', Record<never, never>, Record<never, never>>,
    '/demo/dev/icons': RouteRecordInfo<'/demo/dev/icons', '/demo/dev/icons', Record<never, never>, Record<never, never>>,
    '/demo/errors/': RouteRecordInfo<'/demo/errors/', '/demo/errors', Record<never, never>, Record<never, never>>,
    '/demo/errors/401': RouteRecordInfo<'/demo/errors/401', '/demo/errors/401', Record<never, never>, Record<never, never>>,
    '/demo/errors/403': RouteRecordInfo<'/demo/errors/403', '/demo/errors/403', Record<never, never>, Record<never, never>>,
    '/demo/errors/404': RouteRecordInfo<'/demo/errors/404', '/demo/errors/404', Record<never, never>, Record<never, never>>,
    '/demo/errors/500': RouteRecordInfo<'/demo/errors/500', '/demo/errors/500', Record<never, never>, Record<never, never>>,
    '/demo/errors/503': RouteRecordInfo<'/demo/errors/503', '/demo/errors/503', Record<never, never>, Record<never, never>>,
    '/demo/forms/advanced': RouteRecordInfo<'/demo/forms/advanced', '/demo/forms/advanced', Record<never, never>, Record<never, never>>,
    '/demo/forms/basic': RouteRecordInfo<'/demo/forms/basic', '/demo/forms/basic', Record<never, never>, Record<never, never>>,
    '/demo/forms/upload': RouteRecordInfo<'/demo/forms/upload', '/demo/forms/upload', Record<never, never>, Record<never, never>>,
    '/demo/forms/validation': RouteRecordInfo<'/demo/forms/validation', '/demo/forms/validation', Record<never, never>, Record<never, never>>,
    '/demo/help/contact': RouteRecordInfo<'/demo/help/contact', '/demo/help/contact', Record<never, never>, Record<never, never>>,
    '/demo/help/faq': RouteRecordInfo<'/demo/help/faq', '/demo/help/faq', Record<never, never>, Record<never, never>>,
    '/demo/help/help-center': RouteRecordInfo<'/demo/help/help-center', '/demo/help/help-center', Record<never, never>, Record<never, never>>,
    '/demo/help/tutorials': RouteRecordInfo<'/demo/help/tutorials', '/demo/help/tutorials', Record<never, never>, Record<never, never>>,
    '/demo/poetry/': RouteRecordInfo<'/demo/poetry/', '/demo/poetry', Record<never, never>, Record<never, never>>,
    '/demo/settings/': RouteRecordInfo<'/demo/settings/', '/demo/settings', Record<never, never>, Record<never, never>>,
    '/demo/settings/account': RouteRecordInfo<'/demo/settings/account', '/demo/settings/account', Record<never, never>, Record<never, never>>,
    '/demo/settings/appearance': RouteRecordInfo<'/demo/settings/appearance', '/demo/settings/appearance', Record<never, never>, Record<never, never>>,
    '/demo/settings/display': RouteRecordInfo<'/demo/settings/display', '/demo/settings/display', Record<never, never>, Record<never, never>>,
    '/demo/settings/notifications': RouteRecordInfo<'/demo/settings/notifications', '/demo/settings/notifications', Record<never, never>, Record<never, never>>,
    '/demo/sva-components/': RouteRecordInfo<'/demo/sva-components/', '/demo/sva-components', Record<never, never>, Record<never, never>>,
    '/demo/tasks/': RouteRecordInfo<'/demo/tasks/', '/demo/tasks', Record<never, never>, Record<never, never>>,
    '/demo/tutorials/': RouteRecordInfo<'/demo/tutorials/', '/demo/tutorials', Record<never, never>, Record<never, never>>,
    '/demo/users/': RouteRecordInfo<'/demo/users/', '/demo/users', Record<never, never>, Record<never, never>>,
    '/system/': RouteRecordInfo<'/system/', '/system', Record<never, never>, Record<never, never>>,
    '/system/access-control/': RouteRecordInfo<'/system/access-control/', '/system/access-control', Record<never, never>, Record<never, never>>,
    '/system/alert-monitoring/': RouteRecordInfo<'/system/alert-monitoring/', '/system/alert-monitoring', Record<never, never>, Record<never, never>>,
    '/system/alerts/': RouteRecordInfo<'/system/alerts/', '/system/alerts', Record<never, never>, Record<never, never>>,
    '/system/audit/': RouteRecordInfo<'/system/audit/', '/system/audit', Record<never, never>, Record<never, never>>,
    '/system/authentication/': RouteRecordInfo<'/system/authentication/', '/system/authentication', Record<never, never>, Record<never, never>>,
    '/system/backup/': RouteRecordInfo<'/system/backup/', '/system/backup', Record<never, never>, Record<never, never>>,
    '/system/capacity/': RouteRecordInfo<'/system/capacity/', '/system/capacity', Record<never, never>, Record<never, never>>,
    '/system/database-backup/': RouteRecordInfo<'/system/database-backup/', '/system/database-backup', Record<never, never>, Record<never, never>>,
    '/system/database-optimization/': RouteRecordInfo<'/system/database-optimization/', '/system/database-optimization', Record<never, never>, Record<never, never>>,
    '/system/databases/': RouteRecordInfo<'/system/databases/', '/system/databases', Record<never, never>, Record<never, never>>,
    '/system/disk-monitoring/': RouteRecordInfo<'/system/disk-monitoring/', '/system/disk-monitoring', Record<never, never>, Record<never, never>>,
    '/system/dns/': RouteRecordInfo<'/system/dns/', '/system/dns', Record<never, never>, Record<never, never>>,
    '/system/environment/': RouteRecordInfo<'/system/environment/', '/system/environment', Record<never, never>, Record<never, never>>,
    '/system/firewall/': RouteRecordInfo<'/system/firewall/', '/system/firewall', Record<never, never>, Record<never, never>>,
    '/system/load-balancing/': RouteRecordInfo<'/system/load-balancing/', '/system/load-balancing', Record<never, never>, Record<never, never>>,
    '/system/log-monitoring/': RouteRecordInfo<'/system/log-monitoring/', '/system/log-monitoring', Record<never, never>, Record<never, never>>,
    '/system/monitoring/': RouteRecordInfo<'/system/monitoring/', '/system/monitoring', Record<never, never>, Record<never, never>>,
    '/system/network/': RouteRecordInfo<'/system/network/', '/system/network', Record<never, never>, Record<never, never>>,
    '/system/operation-logs/': RouteRecordInfo<'/system/operation-logs/', '/system/operation-logs', Record<never, never>, Record<never, never>>,
    '/system/parameters/': RouteRecordInfo<'/system/parameters/', '/system/parameters', Record<never, never>, Record<never, never>>,
    '/system/performance/': RouteRecordInfo<'/system/performance/', '/system/performance', Record<never, never>, Record<never, never>>,
    '/system/permissions/': RouteRecordInfo<'/system/permissions/', '/system/permissions', Record<never, never>, Record<never, never>>,
    '/system/resources/': RouteRecordInfo<'/system/resources/', '/system/resources', Record<never, never>, Record<never, never>>,
    '/system/roles/': RouteRecordInfo<'/system/roles/', '/system/roles', Record<never, never>, Record<never, never>>,
    '/system/security/': RouteRecordInfo<'/system/security/', '/system/security', Record<never, never>, Record<never, never>>,
    '/system/security-audit/': RouteRecordInfo<'/system/security-audit/', '/system/security-audit', Record<never, never>, Record<never, never>>,
    '/system/security-logs/': RouteRecordInfo<'/system/security-logs/', '/system/security-logs', Record<never, never>, Record<never, never>>,
    '/system/server-config/': RouteRecordInfo<'/system/server-config/', '/system/server-config', Record<never, never>, Record<never, never>>,
    '/system/server-status/': RouteRecordInfo<'/system/server-status/', '/system/server-status', Record<never, never>, Record<never, never>>,
    '/system/servers/': RouteRecordInfo<'/system/servers/', '/system/servers', Record<never, never>, Record<never, never>>,
    '/system/session/': RouteRecordInfo<'/system/session/', '/system/session', Record<never, never>, Record<never, never>>,
    '/system/settings/': RouteRecordInfo<'/system/settings/', '/system/settings', Record<never, never>, Record<never, never>>,
    '/system/storage/': RouteRecordInfo<'/system/storage/', '/system/storage', Record<never, never>, Record<never, never>>,
    '/system/terminal/': RouteRecordInfo<'/system/terminal/', '/system/terminal', Record<never, never>, Record<never, never>>,
    '/system/users/': RouteRecordInfo<'/system/users/', '/system/users', Record<never, never>, Record<never, never>>,
    '/system/vulnerability-scan/': RouteRecordInfo<'/system/vulnerability-scan/', '/system/vulnerability-scan', Record<never, never>, Record<never, never>>,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the volar plugin to automatically type useRoute()
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes: '/'
      views: never
    }
    'src/pages/[...path].vue': {
      routes: '/[...path]'
      views: never
    }
    'src/pages/auth.vue': {
      routes: '/auth' | '/auth/' | '/auth/forgot-password' | '/auth/otp' | '/auth/sign-in' | '/auth/sign-in-2' | '/auth/sign-up'
      views: 'default'
    }
    'src/pages/auth/index.vue': {
      routes: '/auth/'
      views: never
    }
    'src/pages/auth/forgot-password.vue': {
      routes: '/auth/forgot-password'
      views: never
    }
    'src/pages/auth/otp.vue': {
      routes: '/auth/otp'
      views: never
    }
    'src/pages/auth/sign-in.vue': {
      routes: '/auth/sign-in'
      views: never
    }
    'src/pages/auth/sign-in-2.vue': {
      routes: '/auth/sign-in-2'
      views: never
    }
    'src/pages/auth/sign-up.vue': {
      routes: '/auth/sign-up'
      views: never
    }
    'src/pages/demo/index.vue': {
      routes: '/demo/'
      views: never
    }
    'src/pages/demo/ai-talk/index.vue': {
      routes: '/demo/ai-talk/'
      views: never
    }
    'src/pages/demo/analytics/index.vue': {
      routes: '/demo/analytics/'
      views: never
    }
    'src/pages/demo/apps/index.vue': {
      routes: '/demo/apps/'
      views: never
    }
    'src/pages/demo/auth/index.vue': {
      routes: '/demo/auth/'
      views: never
    }
    'src/pages/demo/auth/forgot-password.vue': {
      routes: '/demo/auth/forgot-password'
      views: never
    }
    'src/pages/demo/auth/otp.vue': {
      routes: '/demo/auth/otp'
      views: never
    }
    'src/pages/demo/auth/sign-in.vue': {
      routes: '/demo/auth/sign-in'
      views: never
    }
    'src/pages/demo/auth/sign-in-2.vue': {
      routes: '/demo/auth/sign-in-2'
      views: never
    }
    'src/pages/demo/auth/sign-up.vue': {
      routes: '/demo/auth/sign-up'
      views: never
    }
    'src/pages/demo/billing/index.vue': {
      routes: '/demo/billing/'
      views: never
    }
    'src/pages/demo/dev/api-docs.vue': {
      routes: '/demo/dev/api-docs'
      views: never
    }
    'src/pages/demo/dev/examples.vue': {
      routes: '/demo/dev/examples'
      views: never
    }
    'src/pages/demo/dev/icons.vue': {
      routes: '/demo/dev/icons'
      views: never
    }
    'src/pages/demo/errors/index.vue': {
      routes: '/demo/errors/'
      views: never
    }
    'src/pages/demo/errors/401.vue': {
      routes: '/demo/errors/401'
      views: never
    }
    'src/pages/demo/errors/403.vue': {
      routes: '/demo/errors/403'
      views: never
    }
    'src/pages/demo/errors/404.vue': {
      routes: '/demo/errors/404'
      views: never
    }
    'src/pages/demo/errors/500.vue': {
      routes: '/demo/errors/500'
      views: never
    }
    'src/pages/demo/errors/503.vue': {
      routes: '/demo/errors/503'
      views: never
    }
    'src/pages/demo/forms/advanced.vue': {
      routes: '/demo/forms/advanced'
      views: never
    }
    'src/pages/demo/forms/basic.vue': {
      routes: '/demo/forms/basic'
      views: never
    }
    'src/pages/demo/forms/upload.vue': {
      routes: '/demo/forms/upload'
      views: never
    }
    'src/pages/demo/forms/validation.vue': {
      routes: '/demo/forms/validation'
      views: never
    }
    'src/pages/demo/help/contact.vue': {
      routes: '/demo/help/contact'
      views: never
    }
    'src/pages/demo/help/faq.vue': {
      routes: '/demo/help/faq'
      views: never
    }
    'src/pages/demo/help/help-center.vue': {
      routes: '/demo/help/help-center'
      views: never
    }
    'src/pages/demo/help/tutorials.vue': {
      routes: '/demo/help/tutorials'
      views: never
    }
    'src/pages/demo/poetry/index.vue': {
      routes: '/demo/poetry/'
      views: never
    }
    'src/pages/demo/settings/index.vue': {
      routes: '/demo/settings/'
      views: never
    }
    'src/pages/demo/settings/account.vue': {
      routes: '/demo/settings/account'
      views: never
    }
    'src/pages/demo/settings/appearance.vue': {
      routes: '/demo/settings/appearance'
      views: never
    }
    'src/pages/demo/settings/display.vue': {
      routes: '/demo/settings/display'
      views: never
    }
    'src/pages/demo/settings/notifications.vue': {
      routes: '/demo/settings/notifications'
      views: never
    }
    'src/pages/demo/sva-components/index.vue': {
      routes: '/demo/sva-components/'
      views: never
    }
    'src/pages/demo/tasks/index.vue': {
      routes: '/demo/tasks/'
      views: never
    }
    'src/pages/demo/tutorials/index.vue': {
      routes: '/demo/tutorials/'
      views: never
    }
    'src/pages/demo/users/index.vue': {
      routes: '/demo/users/'
      views: never
    }
    'src/pages/system/index.vue': {
      routes: '/system/'
      views: never
    }
    'src/pages/system/access-control/index.vue': {
      routes: '/system/access-control/'
      views: never
    }
    'src/pages/system/alert-monitoring/index.vue': {
      routes: '/system/alert-monitoring/'
      views: never
    }
    'src/pages/system/alerts/index.vue': {
      routes: '/system/alerts/'
      views: never
    }
    'src/pages/system/audit/index.vue': {
      routes: '/system/audit/'
      views: never
    }
    'src/pages/system/authentication/index.vue': {
      routes: '/system/authentication/'
      views: never
    }
    'src/pages/system/backup/index.vue': {
      routes: '/system/backup/'
      views: never
    }
    'src/pages/system/capacity/index.vue': {
      routes: '/system/capacity/'
      views: never
    }
    'src/pages/system/database-backup/index.vue': {
      routes: '/system/database-backup/'
      views: never
    }
    'src/pages/system/database-optimization/index.vue': {
      routes: '/system/database-optimization/'
      views: never
    }
    'src/pages/system/databases/index.vue': {
      routes: '/system/databases/'
      views: never
    }
    'src/pages/system/disk-monitoring/index.vue': {
      routes: '/system/disk-monitoring/'
      views: never
    }
    'src/pages/system/dns/index.vue': {
      routes: '/system/dns/'
      views: never
    }
    'src/pages/system/environment/index.vue': {
      routes: '/system/environment/'
      views: never
    }
    'src/pages/system/firewall/index.vue': {
      routes: '/system/firewall/'
      views: never
    }
    'src/pages/system/load-balancing/index.vue': {
      routes: '/system/load-balancing/'
      views: never
    }
    'src/pages/system/log-monitoring/index.vue': {
      routes: '/system/log-monitoring/'
      views: never
    }
    'src/pages/system/monitoring/index.vue': {
      routes: '/system/monitoring/'
      views: never
    }
    'src/pages/system/network/index.vue': {
      routes: '/system/network/'
      views: never
    }
    'src/pages/system/operation-logs/index.vue': {
      routes: '/system/operation-logs/'
      views: never
    }
    'src/pages/system/parameters/index.vue': {
      routes: '/system/parameters/'
      views: never
    }
    'src/pages/system/performance/index.vue': {
      routes: '/system/performance/'
      views: never
    }
    'src/pages/system/permissions/index.vue': {
      routes: '/system/permissions/'
      views: never
    }
    'src/pages/system/resources/index.vue': {
      routes: '/system/resources/'
      views: never
    }
    'src/pages/system/roles/index.vue': {
      routes: '/system/roles/'
      views: never
    }
    'src/pages/system/security/index.vue': {
      routes: '/system/security/'
      views: never
    }
    'src/pages/system/security-audit/index.vue': {
      routes: '/system/security-audit/'
      views: never
    }
    'src/pages/system/security-logs/index.vue': {
      routes: '/system/security-logs/'
      views: never
    }
    'src/pages/system/server-config/index.vue': {
      routes: '/system/server-config/'
      views: never
    }
    'src/pages/system/server-status/index.vue': {
      routes: '/system/server-status/'
      views: never
    }
    'src/pages/system/servers/index.vue': {
      routes: '/system/servers/'
      views: never
    }
    'src/pages/system/session/index.vue': {
      routes: '/system/session/'
      views: never
    }
    'src/pages/system/settings/index.vue': {
      routes: '/system/settings/'
      views: never
    }
    'src/pages/system/storage/index.vue': {
      routes: '/system/storage/'
      views: never
    }
    'src/pages/system/terminal/index.vue': {
      routes: '/system/terminal/'
      views: never
    }
    'src/pages/system/users/index.vue': {
      routes: '/system/users/'
      views: never
    }
    'src/pages/system/vulnerability-scan/index.vue': {
      routes: '/system/vulnerability-scan/'
      views: never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the volar plugin to automatically type useRoute()
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
