// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OpValsInt64 } from '../filter/OpValsInt64'
import type { OpValsString } from '../filter/OpValsString'
import type { OpValsValue } from '../filter/OpValsValue'

/**
 * Filter for querying user info
 */
export type UserInfoFilter = {
  id: OpValsInt64 | null
  user_id: OpValsInt64 | null
  nickname: OpValsString | null
  email: OpValsString | null
  phone: OpValsString | null
  gender: OpValsString | null
  country: OpValsString | null
  province: OpValsString | null
  city: OpValsString | null
  status: OpValsString | null
  cid: OpValsInt64 | null
  ctime: OpValsValue | null
  mid: OpValsInt64 | null
  mtime: OpValsValue | null
}
