// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UserGender } from './UserGender'
import type { UserStatus } from './UserStatus'

/**
 * User info entity
 */
export type UserInfo = {
  id: bigint
  user_id: bigint
  nickname: string | null
  avatar: string | null
  bio: string | null
  email: string | null
  email_verified: boolean
  phone: string | null
  phone_verified: boolean
  gender: UserGender
  birthday: string | null
  country: string | null
  province: string | null
  city: string | null
  address: string | null
  postal_code: string | null
  timezone: string | null
  locale: string | null
  theme: string | null
  status: UserStatus
  last_login_at: string | null
  last_login_ip: string | null
  login_count: number
  cid: bigint
  ctime: string
  mid: bigint
  mtime: string
}
