// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UserGender } from './UserGender'
import type { UserStatus } from './UserStatus'
import type { UserTyp } from './UserTyp'

/**
 * User with info - combined view of user and user_info
 */
export type UserWithInfo = {
  id: bigint
  username: string
  typ: UserTyp
  ctime: string
  mtime: string
  user_info_id: bigint | null
  nickname: string | null
  avatar: string | null
  bio: string | null
  email: string | null
  email_verified: boolean | null
  phone: string | null
  phone_verified: boolean | null
  gender: UserGender | null
  birthday: string | null
  country: string | null
  province: string | null
  city: string | null
  address: string | null
  postal_code: string | null
  timezone: string | null
  locale: string | null
  theme: string | null
  status: UserStatus | null
  last_login_at: string | null
  last_login_ip: string | null
  login_count: number | null
}
