// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * User status
 */
export type UserStatus = 'Active' | 'Inactive' | 'Suspended' | 'Deleted'
