use lib_core::model::agent::{
	Agent, AgentBmc, AgentFilter, AgentForCreate, AgentForUpdate,
};
use lib_rest_core::prelude::*;
use lib_web::middleware::mw_auth::CtxW;
use serde::{Deserialize, Serialize};

generate_common_rest_fns!(
	Bmc: AgentBmc,
	Entity: Agent,
	ForCreate: AgentForCreate,
	ForUpdate: AgentForUpdate,
	Filter: AgentFilter,
	Suffix: agent,
	ResourceDisplay: "Agent",
	ResourceGroup: "Agent Management",
	ResourceDescription: "agent entity for AI assistants"
);

// region:    --- Custom REST Endpoints

// -- Request/Response types for custom endpoints

#[derive(Debug, Deserialize)]
pub struct CloneAgentPayload {
	pub new_name: String,
}

#[derive(Debug, Serialize)]
pub struct CloneAgentResponse {
	pub original_id: i64,
	pub cloned_id: i64,
	pub cloned_agent: Agent,
}

#[derive(Debug, Serialize)]
pub struct AgentStatsResponse {
	pub total_count: i64,
	pub active_count: i64,
}

// -- Permission registration for custom endpoints

lib_core::register_crud_permissions!("agent_custom", "Agent Custom", "Agent Management", "custom agent operations");

// -- Custom endpoint handlers

/// POST /agents/:id/clone
/// Clone an existing agent with a new name
#[lib_macros::rest_permission(
	key = "agent_custom:create",
	group = "Agent Management",
	display = "Clone Agent",
	description = "Create a copy of an existing agent with a new name"
)]
pub async fn clone_agent(
	ctx: CtxW,
	State(mm): State<ModelManager>,
	Path(PathId { id }): Path<PathId>,
	Json(payload): Json<CloneAgentPayload>,
) -> Result<RestCreated<CloneAgentResponse>> {
	// Permission check is automatically injected!

	// Get original agent
	let original = AgentBmc::get(&ctx.0, &mm, id).await?;

	// Create cloned agent with new name
	let agent_c = AgentForCreate {
		name: payload.new_name,
	};
	let cloned_id = AgentBmc::create(&ctx.0, &mm, agent_c).await?;
	let cloned_agent = AgentBmc::get(&ctx.0, &mm, cloned_id).await?;

	Ok(CloneAgentResponse {
		original_id: original.id,
		cloned_id,
		cloned_agent,
	}.into())
}

/// GET /agents/stats
/// Get agent statistics
#[lib_macros::rest_permission(
	key = "agent_custom:read",
	group = "Agent Management",
	display = "Get Agent Stats",
	description = "View agent statistics including total and active counts"
)]
pub async fn get_agent_stats(
	ctx: CtxW,
	State(mm): State<ModelManager>,
) -> Result<RestResponse<AgentStatsResponse>> {
	// Permission check is automatically injected!

	// Get total count
	let total_count = AgentBmc::count(&ctx.0, &mm, None).await?;

	// For demo, active_count = total_count (no status field yet)
	let active_count = total_count;

	Ok(AgentStatsResponse {
		total_count,
		active_count,
	}.into())
}

/// Build custom agent routes (not generated by macro)
pub fn custom_agent_routes() -> axum::Router<ModelManager> {
	use lib_core::generate_custom_rest_routes;

	// generate_custom_rest_routes! validates AND builds router in one step
	// No need to maintain two separate lists!
	generate_custom_rest_routes!(
		get "/stats" => get_agent_stats,
		post "/{id}/clone" => clone_agent,
		get "/{id}/export" => export_agent,
		post "/{id}/archive" => archive_agent,
		get "/report" => agent_report,
		get "/{id}/view" => view_agent,
	)
}

// endregion: --- Custom REST Endpoints

// region:    --- Macro-based Permission Endpoints (Demo)

// -- Response types

#[derive(Debug, Serialize)]
pub struct ExportAgentResponse {
	pub id: i64,
	pub name: String,
	pub export_format: String,
}

#[derive(Debug, Serialize)]
pub struct ArchiveAgentResponse {
	pub id: i64,
	pub archived: bool,
}

#[derive(Debug, Serialize)]
pub struct AgentReportResponse {
	pub total: i64,
	pub report_type: String,
}

/// Demo 1: #[register_permission] - Only registers the permission, no runtime check
/// The permission will be synced to database at startup.
/// Manual check still needed.
#[lib_macros::register_permission(
	key = "agent:export",
	group = "Agent Management",
	display = "Export Agent",
	description = "Export agent data in various formats"
)]
pub async fn export_agent(
	ctx: CtxW,
	State(mm): State<ModelManager>,
	Path(PathId { id }): Path<PathId>,
) -> Result<RestResponse<ExportAgentResponse>> {
	let ctx = ctx.0;
	// Manual permission check (register_permission only registers, not checks)
	ctx.require_permission("agent:export")?;

	let agent = AgentBmc::get(&ctx, &mm, id).await?;

	Ok(ExportAgentResponse {
		id: agent.id,
		name: agent.name,
		export_format: "json".to_string(),
	}.into())
}

/// Demo 2: #[rest_permission] - Both registers AND checks (recommended for REST)
/// Uses ctx.0 automatically for CtxW wrapper!
#[lib_macros::rest_permission(
	key = "agent:archive",
	group = "Agent Management",
	display = "Archive Agent",
	description = "Archive an agent to mark it as inactive"
)]
pub async fn archive_agent(
	ctx: CtxW,
	State(mm): State<ModelManager>,
	Path(PathId { id }): Path<PathId>,
) -> Result<RestResponse<ArchiveAgentResponse>> {
	// Permission check is automatically injected by #[rest_permission]!
	let _agent = AgentBmc::get(&ctx.0, &mm, id).await?;

	Ok(ArchiveAgentResponse {
		id,
		archived: true,
	}.into())
}

/// Demo 3: #[rest_require_permissions] - Check multiple permissions (ALL must pass)
/// Auto-injects ctx.0.require_all_permissions()
#[lib_macros::rest_require_permissions("agent:read", "agent_custom:read")]
pub async fn agent_report(
	ctx: CtxW,
	State(mm): State<ModelManager>,
) -> Result<RestResponse<AgentReportResponse>> {
	// Permission checks are automatically injected!
	let total = AgentBmc::count(&ctx.0, &mm, None).await?;

	Ok(AgentReportResponse {
		total,
		report_type: "summary".to_string(),
	}.into())
}

/// Demo 4: #[rest_require_any_permission] - Check multiple permissions (ANY one passes)
/// Auto-injects ctx.0.require_any_permission()
#[lib_macros::rest_require_any_permission("agent:read", "agent_custom:read")]
pub async fn view_agent(
	ctx: CtxW,
	State(mm): State<ModelManager>,
	Path(PathId { id }): Path<PathId>,
) -> Result<RestResponse<Agent>> {
	// Permission check is automatically injected!
	let agent = AgentBmc::get(&ctx.0, &mm, id).await?;
	Ok(agent.into())
}

// endregion: --- Macro-based Permission Endpoints (Demo)
