---- User Info Schema

-- Enums
CREATE TYPE user_gender AS ENUM ('Unknown', 'Male', 'Female');
CREATE TYPE user_status AS ENUM ('Active', 'Inactive', 'Suspended', 'Deleted');

-- User Info Table
CREATE TABLE "user_info" (
  -- PK & FK
  id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,
  user_id BIGINT NOT NULL UNIQUE REFERENCES "user"(id) ON DELETE CASCADE,

  -- Basic Info
  nickname VARCHAR(64),
  avatar VARCHAR(512),
  bio VARCHAR(500),

  -- Contact
  email VARCHAR(128),
  email_verified BOOLEAN NOT NULL DEFAULT false,
  phone VARCHAR(32),
  phone_verified BOOLEAN NOT NULL DEFAULT false,

  -- Personal Attributes
  gender user_gender NOT NULL DEFAULT 'Unknown',
  birthday DATE,
  country VARCHAR(64),
  province VARCHAR(64),
  city VARCHAR(64),
  address VARCHAR(256),
  postal_code VARCHAR(16),
  timezone VARCHAR(64),
  locale VARCHAR(16),
  theme VARCHAR(32),

  -- Account Status
  status user_status NOT NULL DEFAULT 'Active',
  last_login_at TIMESTAMPTZ,
  last_login_ip VARCHAR(64),
  login_count INTEGER NOT NULL DEFAULT 0,

  -- Timestamps
  cid BIGINT NOT NULL,
  ctime TIMESTAMPTZ NOT NULL,
  mid BIGINT NOT NULL,
  mtime TIMESTAMPTZ NOT NULL
);

-- Indexes
CREATE INDEX idx_user_info_email ON user_info(email) WHERE email IS NOT NULL;
CREATE INDEX idx_user_info_phone ON user_info(phone) WHERE phone IS NOT NULL;
CREATE INDEX idx_user_info_status ON user_info(status);
