// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Lightweight permission for listing
 */
export type PermissionLite = {
  id: bigint
  key: string
  group_name: string | null
  display_name: string | null
}
