[app]
web_folder = "web-folder/"

[db]
url = "postgres://app_user:dev_only_pwd@localhost:5432/app_db"

[auth]
token_duration_sec = 1800

[valkey]
url = "redis://localhost:6379"
pool_max_size = 10
pool_min_idle = 2

[cache]
permission_enabled = false
model_enabled = false

[initial_admin]
username = "admin"
