-- ACS (Access Control System) Schema
-- Permission-based access control tables

-- Permission table
-- Stores all available permissions in the system
CREATE TABLE permission (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,

  -- Permission key (unique identifier, e.g., "agent:create", "user:delete")
  key VARCHAR(100) NOT NULL UNIQUE,
  
  -- Display information
  group_name VARCHAR(50),        -- Group for UI display (e.g., "Agent管理", "用户管理")
  display_name VARCHAR(100),     -- Human-readable name (e.g., "创建Agent")
  description TEXT,              -- Optional description

  -- Timestamps
  cid BIGINT NOT NULL,
  ctime TIMESTAMP WITH TIME ZONE NOT NULL,
  mid BIGINT NOT NULL,
  mtime TIMESTAMP WITH TIME ZONE NOT NULL
);

-- Create index for group_name for faster grouping queries
CREATE INDEX idx_permission_group_name ON permission(group_name);


-- Role table
-- Stores roles that can be assigned to users
CREATE TABLE role (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,

  -- Role name (unique identifier)
  name VARCHAR(50) NOT NULL UNIQUE,
  
  -- Display information
  display_name VARCHAR(100),     -- Human-readable name
  description TEXT,              -- Optional description

  -- Timestamps
  cid BIGINT NOT NULL,
  ctime TIMESTAMP WITH TIME ZONE NOT NULL,
  mid BIGINT NOT NULL,
  mtime TIMESTAMP WITH TIME ZONE NOT NULL
);


-- Role-Permission junction table
-- Many-to-many relationship between roles and permissions
CREATE TABLE role_permission (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,

  -- Foreign keys
  role_id BIGINT NOT NULL,
  permission_id BIGINT NOT NULL,

  -- Unique constraint to prevent duplicates
  UNIQUE (role_id, permission_id),

  -- Timestamps
  cid BIGINT NOT NULL,
  ctime TIMESTAMP WITH TIME ZONE NOT NULL,
  mid BIGINT NOT NULL,
  mtime TIMESTAMP WITH TIME ZONE NOT NULL
);

-- Add foreign key constraints
ALTER TABLE role_permission ADD CONSTRAINT fk_role_permission_role
  FOREIGN KEY (role_id) REFERENCES role(id)
  ON DELETE CASCADE;

ALTER TABLE role_permission ADD CONSTRAINT fk_role_permission_permission
  FOREIGN KEY (permission_id) REFERENCES permission(id)
  ON DELETE CASCADE;

-- Create indexes for faster lookups
CREATE INDEX idx_role_permission_role_id ON role_permission(role_id);
CREATE INDEX idx_role_permission_permission_id ON role_permission(permission_id);


-- User-Role junction table
-- Many-to-many relationship between users and roles
CREATE TABLE user_role (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,

  -- Foreign keys
  user_id BIGINT NOT NULL,
  role_id BIGINT NOT NULL,

  -- Unique constraint to prevent duplicates
  UNIQUE (user_id, role_id),

  -- Timestamps
  cid BIGINT NOT NULL,
  ctime TIMESTAMP WITH TIME ZONE NOT NULL,
  mid BIGINT NOT NULL,
  mtime TIMESTAMP WITH TIME ZONE NOT NULL
);

-- Add foreign key constraints
ALTER TABLE user_role ADD CONSTRAINT fk_user_role_user
  FOREIGN KEY (user_id) REFERENCES "user"(id)
  ON DELETE CASCADE;

ALTER TABLE user_role ADD CONSTRAINT fk_user_role_role
  FOREIGN KEY (role_id) REFERENCES role(id)
  ON DELETE CASCADE;

-- Create indexes for faster lookups
CREATE INDEX idx_user_role_user_id ON user_role(user_id);
CREATE INDEX idx_user_role_role_id ON user_role(role_id);
