use lib_rpc_core::prelude::*;
use lib_core::model::agent::{
	Agent, AgentBmc, AgentFilter, AgentForCreate, AgentForUpdate,
};
use lib_core::validated_rpc_router;
use rpc_router::{IntoParams, IntoDefaultRpcParams};
use serde::{Deserialize, Serialize};

pub fn rpc_router_builder() -> RouterBuilder {
	// validated_rpc_router! validates all handlers have permission annotations
	// AND builds the router - no need for separate validation call
	validated_rpc_router!(
		// -- CRUD (generated by generate_common_rpc_fns!)
		create_agent,
		get_agent,
		list_agents,
		update_agent,
		delete_agent,
		// -- Custom handlers (each must have #[permission] macro)
		clone_agent,
		get_agent_stats,
		batch_delete_agents,
		export_agent,
		archive_agent,
		agent_report,
	)
}

generate_common_rpc_fns!(
	Bmc: AgentBmc,
	Entity: Agent,
	ForCreate: AgentForCreate,
	ForUpdate: AgentForUpdate,
	Filter: AgentFilter,
	Suffix: agent,
	ResourceDisplay: "Agent",
	ResourceGroup: "Agent Management",
	ResourceDescription: "agent entity for AI assistants"
);

// region:    --- Custom RPC Endpoints

// -- Request/Response types for custom RPC

#[derive(Debug, Deserialize)]
pub struct CloneAgentParams {
	pub id: i64,
	pub new_name: String,
}
impl IntoParams for CloneAgentParams {}

#[derive(Debug, Serialize)]
pub struct CloneAgentResult {
	pub original_id: i64,
	pub cloned_id: i64,
	pub cloned_agent: Agent,
}

#[derive(Debug, Deserialize, Default)]
pub struct AgentStatsParams {}
impl IntoDefaultRpcParams for AgentStatsParams {}

#[derive(Debug, Serialize)]
pub struct AgentStatsResult {
	pub total_count: i64,
	pub active_count: i64,
}

#[derive(Debug, Deserialize)]
pub struct BatchDeleteParams {
	pub ids: Vec<i64>,
}
impl IntoParams for BatchDeleteParams {}

#[derive(Debug, Serialize)]
pub struct BatchDeleteResult {
	pub deleted_count: u64,
}

// -- Permission registration for custom RPC

lib_core::register_crud_permissions!("agent_custom", "Agent Custom", "Agent Management", "custom agent operations");

// -- Custom RPC handlers

/// Clone an existing agent with a new name
/// RPC method: clone_agent
#[lib_macros::permission(
	key = "agent_custom:create",
	group = "Agent Management",
	display = "Clone Agent",
	description = "Create a copy of an existing agent with a new name"
)]
pub async fn clone_agent(
	ctx: Ctx,
	mm: ModelManager,
	params: CloneAgentParams,
) -> Result<DataRpcResult<CloneAgentResult>> {
	// Permission check is automatically injected!

	// Get original agent
	let original = AgentBmc::get(&ctx, &mm, params.id).await?;

	// Create cloned agent with new name
	let agent_c = AgentForCreate {
		name: params.new_name,
	};
	let cloned_id = AgentBmc::create(&ctx, &mm, agent_c).await?;
	let cloned_agent = AgentBmc::get(&ctx, &mm, cloned_id).await?;

	Ok(CloneAgentResult {
		original_id: original.id,
		cloned_id,
		cloned_agent,
	}.into())
}

/// Get agent statistics
/// RPC method: get_agent_stats
#[lib_macros::permission(
	key = "agent_custom:read",
	group = "Agent Management",
	display = "Get Agent Stats",
	description = "View agent statistics including total and active counts"
)]
pub async fn get_agent_stats(
	ctx: Ctx,
	mm: ModelManager,
	_params: AgentStatsParams,
) -> Result<DataRpcResult<AgentStatsResult>> {
	// Permission check is automatically injected!

	// Get total count
	let total_count = AgentBmc::count(&ctx, &mm, None).await?;

	// For demo, active_count = total_count (no status field yet)
	let active_count = total_count;

	Ok(AgentStatsResult {
		total_count,
		active_count,
	}.into())
}

/// Batch delete multiple agents
/// RPC method: batch_delete_agents
#[lib_macros::permission(
	key = "agent:delete",
	group = "Agent Management",
	display = "Batch Delete Agents",
	description = "Delete multiple agents in a single operation"
)]
pub async fn batch_delete_agents(
	ctx: Ctx,
	mm: ModelManager,
	params: BatchDeleteParams,
) -> Result<DataRpcResult<BatchDeleteResult>> {
	// Permission check is automatically injected!

	let deleted_count = AgentBmc::delete_many(&ctx, &mm, params.ids).await?;

	Ok(BatchDeleteResult { deleted_count }.into())
}

// endregion: --- Custom RPC Endpoints

// region:    --- Macro-based Permission RPC Endpoints (Demo)

// -- Request/Response types for macro-based RPC

#[derive(Debug, Deserialize)]
pub struct ExportAgentParams {
	pub id: i64,
	pub format: Option<String>,
}
impl IntoParams for ExportAgentParams {}

#[derive(Debug, Serialize)]
pub struct ExportAgentResult {
	pub id: i64,
	pub name: String,
	pub format: String,
}

#[derive(Debug, Deserialize)]
pub struct ArchiveAgentParams {
	pub id: i64,
}
impl IntoParams for ArchiveAgentParams {}

#[derive(Debug, Serialize)]
pub struct ArchiveAgentResult {
	pub id: i64,
	pub archived: bool,
}

#[derive(Debug, Deserialize, Default)]
pub struct AgentReportParams {}
impl IntoDefaultRpcParams for AgentReportParams {}

#[derive(Debug, Serialize)]
pub struct AgentReportResult {
	pub total: i64,
	pub report_type: String,
}

/// Demo 1: #[register_permission] - Only registers, manual check needed
/// For RPC, you can still use manual ctx.require_permission()
#[lib_macros::register_permission(
	key = "agent:export",
	group = "Agent Management",
	display = "Export Agent",
	description = "Export agent data in various formats"
)]
pub async fn export_agent(
	ctx: Ctx,
	mm: ModelManager,
	params: ExportAgentParams,
) -> Result<DataRpcResult<ExportAgentResult>> {
	// Manual permission check
	ctx.require_permission("agent:export")?;

	let agent = AgentBmc::get(&ctx, &mm, params.id).await?;

	Ok(ExportAgentResult {
		id: agent.id,
		name: agent.name,
		format: params.format.unwrap_or_else(|| "json".to_string()),
	}.into())
}

/// Demo 2: #[permission] - Both registers AND checks (recommended for RPC)
/// For RPC endpoints, ctx is Ctx so the macro auto-injection works!
#[lib_macros::permission(
	key = "agent:archive",
	group = "Agent Management",
	display = "Archive Agent",
	description = "Archive an agent to mark it as inactive"
)]
pub async fn archive_agent(
	ctx: Ctx,
	mm: ModelManager,
	params: ArchiveAgentParams,
) -> Result<DataRpcResult<ArchiveAgentResult>> {
	// Permission check is automatically injected by #[permission] macro!
	let _agent = AgentBmc::get(&ctx, &mm, params.id).await?;

	Ok(ArchiveAgentResult {
		id: params.id,
		archived: true,
	}.into())
}

/// Demo 3: #[require_permissions] - Check multiple permissions (ALL must pass)
/// Auto-injects permission checks for RPC
#[lib_macros::require_permissions("agent:read", "agent_custom:read")]
pub async fn agent_report(
	ctx: Ctx,
	mm: ModelManager,
	_params: AgentReportParams,
) -> Result<DataRpcResult<AgentReportResult>> {
	// Both permission checks are automatically injected!
	let total = AgentBmc::count(&ctx, &mm, None).await?;

	Ok(AgentReportResult {
		total,
		report_type: "summary".to_string(),
	}.into())
}

// endregion: --- Macro-based Permission RPC Endpoints (Demo)
