use lib_core::model::conv::{
	Conv, ConvBmc, ConvFilter, ConvForCreate, ConvForUpdate,
};
use lib_core::model::conv_msg::{ConvMsg, ConvMsgForCreate};
use lib_core::validated_rpc_router;
use lib_rpc_core::prelude::*;

pub fn rpc_router_builder() -> RouterBuilder {
	validated_rpc_router!(
		// -- CRUD (generated by generate_common_rpc_fns!)
		create_conv,
		get_conv,
		list_convs,
		update_conv,
		delete_conv,
		// -- Custom
		add_conv_msg,
	)
}

generate_common_rpc_fns!(
	Bmc: ConvBmc,
	Entity: Conv,
	ForCreate: ConvForCreate,
	ForUpdate: ConvForUpdate,
	Filter: ConvFilter,
	Suffix: conv,
	ResourceDisplay: "Conversation",
	ResourceGroup: "Conversation Management",
	ResourceDescription: "conversation entity for chat sessions"
);

/// Returns conv_msg
#[lib_macros::permission(
	key = "conv_msg:create",
	group = "Conversation Management",
	display = "Add Conversation Message",
	description = "Add a new message to a conversation"
)]
pub async fn add_conv_msg(
	ctx: Ctx,
	mm: ModelManager,
	params: ParamsForCreate<ConvMsgForCreate>,
) -> Result<DataRpcResult<ConvMsg>> {
	let ParamsForCreate { data: msg_c } = params;

	let msg_id = ConvBmc::add_msg(&ctx, &mm, msg_c).await?;
	let msg = ConvBmc::get_msg(&ctx, &mm, msg_id).await?;

	Ok(msg.into())
}

/// Returns conv_msg
#[allow(unused)]
#[lib_macros::permission(
	key = "conv_msg:read",
	group = "Conversation Management",
	display = "Get Conversation Message",
	description = "View a specific message from a conversation"
)]
pub async fn get_conv_msg(
	ctx: Ctx,
	mm: ModelManager,
	params: ParamsIded,
) -> Result<DataRpcResult<ConvMsg>> {
	let ParamsIded { id: msg_id } = params;

	let msg = ConvBmc::get_msg(&ctx, &mm, msg_id).await?;

	Ok(msg.into())
}
