use lib_core::generate_rpc_routes;
use lib_core::model::acs::{Role, RoleBmc, RoleFilter, RoleForCreate, RoleForUpdate};
use lib_rpc_core::prelude::*;

pub fn rpc_router_builder() -> RouterBuilder {
	generate_rpc_routes!(
		// -- CRUD (generated by generate_common_rpc_fns!)
		create_role,
		get_role,
		list_roles,
		update_role,
		delete_role,
	)
}

generate_common_rpc_fns!(
	Bmc: RoleBmc,
	Entity: Role,
	ForCreate: RoleForCreate,
	ForUpdate: RoleForUpdate,
	Filter: RoleFilter,
	Suffix: role,
	ResourceDisplay: "Role",
	ResourceGroup: "Role Management",
	ResourceDescription: "role entity for access control"
);
