use lib_core::generate_rpc_routes;
use lib_core::model::user_info::{
	UserInfo, UserInfoBmc, UserInfoFilter, UserInfoForCreate, UserInfoForUpdate,
};
use lib_rpc_core::prelude::*;
use rpc_router::IntoParams;
use serde::Deserialize;

pub fn rpc_router_builder() -> RouterBuilder {
	generate_rpc_routes!(
		// -- CRUD (generated by generate_common_rpc_fns!)
		create_user_info,
		get_user_info,
		list_user_infos,
		update_user_info,
		delete_user_info,
		// -- Custom handlers
		get_user_info_by_user_id,
		get_current_user_info,
	)
}

generate_common_rpc_fns!(
	Bmc: UserInfoBmc,
	Entity: UserInfo,
	ForCreate: UserInfoForCreate,
	ForUpdate: UserInfoForUpdate,
	Filter: UserInfoFilter,
	Suffix: user_info,
	ResourceDisplay: "User Info",
	ResourceGroup: "User Management",
	ResourceDescription: "user profile information"
);

// region:    --- Custom RPC Endpoints

#[derive(Debug, Deserialize)]
pub struct GetUserInfoByUserIdParams {
	pub user_id: i64,
}
impl IntoParams for GetUserInfoByUserIdParams {}

/// Get user info by user_id (more commonly used)
#[lib_macros::permission(
	key = "user_info:read",
	group = "User Management",
	display = "Get User Info By User ID",
	description = "View user profile information by user ID"
)]
pub async fn get_user_info_by_user_id(
	ctx: Ctx,
	mm: ModelManager,
	params: GetUserInfoByUserIdParams,
) -> Result<DataRpcResult<UserInfo>> {
	let filter = UserInfoFilter {
		user_id: Some(params.user_id.into()),
		..Default::default()
	};

	let user_info = UserInfoBmc::first(&ctx, &mm, Some(vec![filter]), None)
		.await?
		.ok_or(lib_core::model::Error::EntityNotFound {
			entity: "user_info",
			id: params.user_id,
		})?;

	Ok(user_info.into())
}

/// Get current logged-in user's info
#[lib_macros::permission(
	key = "user_info:read",
	group = "User Management",
	display = "Get Current User Info",
	description = "View current logged-in user's profile information"
)]
pub async fn get_current_user_info(
	ctx: Ctx,
	mm: ModelManager,
) -> Result<DataRpcResult<UserInfo>> {
	let user_id = ctx.user_id();

	let filter = UserInfoFilter {
		user_id: Some(user_id.into()),
		..Default::default()
	};

	let user_info = UserInfoBmc::first(&ctx, &mm, Some(vec![filter]), None)
		.await?
		.ok_or(lib_core::model::Error::EntityNotFound {
			entity: "user_info",
			id: user_id,
		})?;

	Ok(user_info.into())
}

// endregion: --- Custom RPC Endpoints
